# This rule is not used by the project argocd-project-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to argocd.platform.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: argocd-project-operator
    app.kubernetes.io/managed-by: kustomize
  name: managedargocdproject-viewer-role
rules:
- apiGroups:
  - argocd.platform.io
  resources:
  - managedargocdprojects
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - argocd.platform.io
  resources:
  - managedargocdprojects/status
  verbs:
  - get
