apiVersion: argocd.platform.io/v1alpha1
kind: ManagedArgoCDProject
metadata:
  labels:
    app.kubernetes.io/name: argocd-project-operator
    app.kubernetes.io/managed-by: kustomize
  name: managedargocdproject-sample
spec:
  # TODO(user): Add fields here
